all: iobound cpubound part1 part2 part3 part4 part5

iobound:
	gcc -g iobound.c -o iobound

cpubound:
	gcc -g cpubound.c -o cpubound

part1: part1.c
	gcc -g part1.c -o part1

part2: part2.c
	gcc -g part2.c -o part2

part3: part3.c
	gcc -g part3.c -o part3

part4: part4.c
	gcc -g part4.c -o part4

part5: part5.c
	gcc -g part5.c -o part5

clean:
	rm iobound cpubound part1 part2 part3 part4 part5